version: "3"
services:
  rails:
    build:
      context: .
      dockerfile: ./ruby/Dockerfile
    environment:
      RAILS_ENV: "development"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "example_root_password"
      MYSQL_HOST: "mysql"
    command: "bundle exec rails server -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - mysql
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "example_root_password"
      MYSQL_DATABASE: "hotelapp_development"
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql
    ports:
      - "33305:3306"

# データ永続化領域
volumes:
  bundle_data:
  mysql_data: